<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="tiles" tilewidth="8" tileheight="8" tilecount="4096" columns="64">
 <editorsettings>
  <export target="tiles.json" format="json"/>
 </editorsettings>
 <image source="../gfx/tiles_spring.png" width="512" height="512"/>
 <tile id="387" type="dry_soil"/>
 <tile id="388" type="dry_soil"/>
 <tile id="389" type="dry_soil"/>
 <tile id="390" type="dry_tilled_soil"/>
 <tile id="391" type="dry_tilled_soil"/>
 <tile id="392" type="dry_tilled_soil"/>
 <tile id="393" type="wet_tilled_soil"/>
 <tile id="394" type="wet_tilled_soil"/>
 <tile id="395" type="wet_tilled_soil"/>
 <tile id="451" type="dry_soil"/>
 <tile id="452" type="dry_soil"/>
 <tile id="453" type="dry_soil"/>
 <tile id="454" type="dry_tilled_soil"/>
 <tile id="455" type="dry_tilled_soil"/>
 <tile id="456" type="dry_tilled_soil"/>
 <tile id="457" type="wet_tilled_soil"/>
 <tile id="458" type="wet_tilled_soil"/>
 <tile id="459" type="wet_tilled_soil"/>
 <tile id="515" type="dry_soil"/>
 <tile id="516" type="dry_soil"/>
 <tile id="517" type="dry_soil"/>
 <tile id="518" type="dry_tilled_soil"/>
 <tile id="519" type="dry_tilled_soil"/>
 <tile id="520" type="dry_tilled_soil"/>
 <tile id="521" type="wet_tilled_soil"/>
 <tile id="522" type="wet_tilled_soil"/>
 <tile id="523" type="wet_tilled_soil"/>
 <tile id="530" type="water"/>
 <tile id="531" type="water"/>
 <tile id="532" type="water"/>
 <tile id="533" type="water"/>
 <tile id="534" type="water"/>
 <tile id="535" type="water"/>
 <tile id="536" type="water"/>
 <tile id="537" type="water"/>
 <tile id="538" type="water"/>
 <tile id="539" type="water"/>
 <tile id="540" type="water"/>
 <tile id="541" type="water"/>
 <tile id="594" type="water"/>
 <tile id="595" type="water"/>
 <tile id="596" type="water"/>
 <tile id="597" type="water"/>
 <tile id="599" type="water"/>
 <tile id="600" type="water"/>
 <tile id="602" type="water"/>
 <tile id="603" type="water"/>
 <tile id="605" type="water"/>
 <tile id="658" type="water"/>
 <tile id="659" type="water"/>
 <tile id="660" type="water"/>
 <tile id="661" type="water"/>
 <tile id="662" type="water"/>
 <tile id="663" type="water"/>
 <tile id="664" type="water"/>
 <tile id="665" type="water"/>
 <tile id="666" type="water"/>
 <tile id="667" type="water"/>
 <tile id="668" type="water"/>
 <tile id="669" type="water"/>
 <tile id="722" type="water"/>
 <tile id="723" type="water"/>
 <tile id="724" type="water"/>
 <tile id="725" type="water"/>
 <tile id="726" type="water"/>
 <tile id="727" type="water"/>
 <tile id="728" type="water"/>
 <tile id="729" type="water"/>
 <tile id="786" type="water"/>
 <tile id="787" type="water"/>
 <tile id="788" type="water"/>
 <tile id="789" type="water"/>
 <tile id="790" type="water"/>
 <tile id="791" type="water"/>
 <tile id="792" type="water"/>
 <tile id="793" type="water"/>
 <tile id="1216" type="rock_small"/>
 <tile id="1218" type="bush_small"/>
 <tile id="1220" type="wood_small"/>
 <tile id="1222" type="grass"/>
 <tile id="1223" type="grass"/>
 <tile id="1286" type="grass"/>
 <tile id="1287" type="grass"/>
</tileset>
